language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1

script:
    - composer lint
    - composer run-test

before_script:
    # Install Nette Tester & Code Checker
    - travis_retry composer install --no-interaction --prefer-dist
