language: php
php:
    - 5.6
    - 7.0
    - 7.1

script:
    - composer lint
    - vendor/bin/tester tests -s -p php $coverage

before_script:
    - travis_retry composer install --no-interaction --prefer-dist
    - if [ $TRAVIS_PHP_VERSION == "7.0" ]; then coverage="-p phpdbg --coverage ./coverage.xml --coverage-src ./src"; fi

after_script:
    # Report Code Coverage
    - >
      if [ "$coverage" != "" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true; fi
