language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

script:
    - composer lint
    - if [ $TRAVIS_PHP_VERSION == "7.1" ]; then temp/nette-coding-standard/ecs check src tests --config temp/nette-coding-standard/coding-standard-php56.neon; fi
    - vendor/bin/tester tests -s -p php $coverage

before_script:
    - travis_retry composer install --no-interaction --prefer-dist
    - if [ $TRAVIS_PHP_VERSION == "7.1" ]; then composer create-project nette/coding-standard temp/nette-coding-standard; fi
    - if [ $TRAVIS_PHP_VERSION == "7.1" ]; then coverage="-p phpdbg --coverage ./coverage.xml --coverage-src ./src"; fi

after_script:
    # Report Code Coverage
    - >
      if [ "$coverage" != "" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true; fi
